namespace ISO23509Calc.Models;

/// <summary>Method used to determine the pitch cone parameters (ISO 23509:2016, 6.2 / Annex A.3).
/// Method 0 is for bevel gears without hypoid offset (a = 0) and needs no iteration. Methods 1-3
/// all cover the general hypoid case and are named after the manufacturing system whose pitch
/// surfaces they reproduce: Method 1 = Gleason, Method 2 = Oerlikon, Method 3 = Klingelnberg.</summary>
public enum PitchConeMethod
{
    Method0,
    Method1,
    Method2,
    Method3
}

/// <summary>Cutting/finishing process (5.6, 5.9 and throughout Clause 7/8): governs whether the
/// lengthwise tooth curvature is a circular arc of radius rc0 (face milling) or an extended
/// epicycloid generated by the relative roll of cutter, cradle and work (face hobbing), which
/// changes the mean-radius-of-curvature formula in the Method 1 iteration (Formula 39 vs 40) and
/// the spiral-angle-at-boundary-point formulas throughout 7.6, 7.7.1 and Clause 8.</summary>
public enum ManufacturingProcess
{
    FaceMilling,
    FaceHobbing
}

/// <summary>Which of the two commonly used forms of tooth-profile initial data (Table 3) is
/// being supplied. Data type I (European-standard style) gives the profile shift coefficient
/// xhm1, the basic crown gear addendum/dedendum factors khap/khfp, and the theoretical thickness
/// modification coefficient xsmn directly. Data type II (AGMA style) gives the equivalent mean
/// addendum factor cham, depth factor kd, clearance factor kc and thickness factor kt instead;
/// Table 4 converts type II into type I before Clause 7 is evaluated, since every printed
/// formula in Clause 7 uses the type I symbols.</summary>
public enum InputDataType
{
    TypeI,
    TypeII
}

/// <summary>Which single backlash quantity (Table 3) is being supplied to derive the thickness
/// modification coefficients xsm1/xsm2 (Formulae 202-205, 207-210). "TheoreticalNoBacklash"
/// uses xsmn directly with no correction (A.4: "for the calculation of the theoretical tooth
/// thickness, the backlash shall be set to zero").</summary>
public enum BacklashMode
{
    TheoreticalNoBacklash,
    OuterNormal_jen,
    OuterTransverse_jet2,
    MeanNormal_jmn,
    MeanTransverse_jmt2
}

/// <summary>How the wheel's addendum angle theta_a2 and dedendum angle theta_f2 (Table 3) are
/// obtained: entered directly, or derived from the depthwise taper type via Annex C.5 (Tables
/// C.4/C.5), which needs the tooth-depth quantities from 7.3 and so is evaluated just before
/// Formula (140).</summary>
public enum ThetaA2Source
{
    Manual,
    AutoFromTaper
}

/// <summary>Depthwise taper type (5.3, Annex C.5, Tables C.4/C.5) used only when
/// <see cref="ThetaA2Source.AutoFromTaper"/> is selected.</summary>
public enum DepthwiseTaper
{
    StandardDepth,
    UniformDepth,
    ConstantSlotWidth,
    ModifiedSlotWidth
}
